# Generated by Django 3.1.14 on 2025-11-24 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='contect',
        ),
        migrations.AlterField(
            model_name='event',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_banners/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('checked_in', 'Checked In')], default='pending_payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='tickets/'),
        ),
    ]
