# Generated by Django 3.1.14 on 2025-11-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
